### ISSUE TITLE
Reading the "prompt" message from the remote device

### ISSUE THREAD

**Issue by rdp137** [fieldrndservices/libssh2lv#10]
when I use putty for SSH comms, I can read the prompt from the device I am talking to.  I can easily see that my last command was completed and the device is ready for the next.  Is this possible using libssh2lv tools?

**Comment by volks73** [comment]
@rdp137 It should be possible, but you will want to create a "shell" using the shell subsystem for a channel instead of an exec sub-system. Since the LabVIEW toolkit is a "thin wrapper" around the libssh2lv library, which is also a "thin wrapper" around the libssh2 library, the libssh2 documentation and examples can also be helpful for context and direction. For example, the [`libssh2_channel_process_startup`](https://libssh2.org/libssh2_channel_process_startup.html) function is used to create the channel type of either `exec` or `shell`. And if you are mildly familiar with C code, the [`ssh2.c`](https://github.com/libssh2/libssh2/blob/master/example/ssh2.c) example can be used as a guide for creating a "shell" that displays the prompt.
