### ISSUE TITLE
Bump libssh2 to v1.11.0

### ISSUE THREAD

**Issue by volks73** [fieldrndservices/libssh2lv#18]
The underlying libssh2 library released a new minor version, v1.11.0, in May 2023. The last release was v1.10.0 back in 2022. A new build of this library using v1.11.0 should be created.

**Comment by hdkim2** [comment]
Hello,
I was getting key exchange errors (Field_RnD_Services_LIBSSH2_Toolkit.lvlib:Session.lvclass:Connect.vi<ERR>
[Key Exchange Failure Error] The encryption key exchange with the remote host has failed) when trying to ssh to servers that did not support ssh-rsa so I was trying to rebuild the source using the Visual Studio command prompt on Windows after changing the dependency to libssh2 v1.11.0 and Openssl v3.2.1 in the CMakeLists file but I am getting errors in the build log about unresolved external symbols. I get the libssh2lv-x64.lib and libssh2lv-x64.exp files but not the libssh2lv-x64.dll file in the bin directory. I was able to compile fine without changing the libssh2 version, could you provide any guidance about what I could be doing wrong? Thank you

**Comment by volks73** [comment]
Can you provide the build log and the exact error messages?

Are you building on a desktop/laptop x86-64 machine?

**Comment by hdkim2** [comment]
I'm using a 64-bit Windows laptop, the errors appear at the very end of the build log
[build.log](https://github.com/user-attachments/files/17909957/build.log)

**Comment by volks73** [comment]
It looks like there are a couple of issues with the Windows build. The OpenSSL is being compiled and linked. Can you verify an OpenSSL DLL is created and available in the ".deps/x64/openssl" folder?

It looks like the libssh2 is also compiled and linked. A static library is created and the dynamic library is not. This is expected as the libssh2lv should statically link the libssh2 library.

However, it appears that during the linking stage for libssh2lv, the libssh2 static library either might not found by the linker or the libssh2 library needs actually be compiled and linked into a dynamic library (DLL) instead of statically linked. 

The `unresolved external symbol` error messages are because the compiler, or linker, cannot find the functions in the libssh2 library (static or dynamic) and cannot create the libssh2lv object file/linking.

It has been awhile since I looked at the build configuration for this library, especially on Windows. Is this Windows 10 or 11?

**Comment by hdkim2** [comment]
It's Windows 11. I compiled both the static and dynamic libraries for OpenSSL and libssh2 and left it linked to the static library and I was able to build and see the .dll file created, thank you for your help. 
[CMakeLists.txt](https://github.com/user-attachments/files/17924961/CMakeLists.txt)
[build.log](https://github.com/user-attachments/files/17925132/build.log)

However when I copied it to the `C:\Program Files \National Instruments\LabVIEW 2024\vi.lib\Field R&D Services\LIBSSH2 for LabVIEW\Toolkit\Support\libssh2lv-x64.dll` location, I got an error when trying to use the Labview VIs:
Error 13 occurred at Call Library Node in Field_RnD_Services_LIBSSH2_Toolkit.lvlib:SSH.lvclass:Initialize.vi
Possible reason(s):
LabVIEW: (Hex 0xD) Failed to load dynamic library because of missing external symbols or dependencies, or because of an invalid file format.
Shareable board exclusively owned.

Are there other dependency files that I should also be copying, or do I need to do something different than just copying the dll file to that location?

**Comment by volks73** [comment]
Glad to hear you were able to get the OpenSSL and libssh2 libraries compiled and resolving the original issue.

Try placing the libssh2.dll in the same directory as the libssh2lv-x86.dll.

There is also an extra space in your path:

```
C:\Program Files \National Instruments\LabVIEW 2024\vi.lib\Field R&D Services\LIBSSH2 for LabVIEW\Toolkit\Support\libssh2lv-x64.dll
```

```
C:\Program Files\National Instruments\LabVIEW 2024\vi.lib\Field R&D Services\LIBSSH2 for LabVIEW\Toolkit\Support\libssh2lv-x64.dll
```

The space might be an issue?

**Comment by hdkim2** [comment]
I added the libssh2.dll and the libcrypto-3-x64.dll to the same path and it worked, and I no longer get key exchange error messages using the VIs. Thank you so much for all your help.

**Comment by volks73** [comment]
Great! I am happy you were able to eventually get your problems resolves and are able to use this toolkit.

I will be closing this issue as it appears the original issue has been resolved.
